### ISSUE TITLE
StartupMacros.fiji.ijm not picked up by ImageJ 1.x

### ISSUE THREAD

**Issue by hinerm** [fiji/fiji#127]
IJ 1.x ships a `Plugins > Macros > Startup Macros` command to open the startup macro file in the script editor.

However, in Fiji this startup macro file is named `StartupMacros.fiji.ijm` which is not compatible with the `Startup Macros` command. Renaming to `StartupMacros.ijm` would fix the problem.

**Comment by hinerm** [comment]
@ctrueden any reason we need the `fiji` in the macro file name?

**Comment by ctrueden** [comment]
Yes, it was put there very intentionally, to avoid conflicts with users' customized `StartupMacros.ijm`. Renaming it cause problems because the Updater would constantly see it as "locally modified" whenever a user edits it.

Of course, Fiji has a mechanism to make it easy _not_ to edit that file, but instead put additions into the `macros/AutoRun` folder. But some people do not use it.

**Comment by ctrueden** [comment]
See also 5287d2c335b6f59b6486ca547a040d7bac2806ac and 6a3e9e13e247fc9d2daa59c4214ee7327f2c4321, although Johannes didn't go into a lot of detail.

**Comment by ctrueden** [comment]
Hmm... maybe it would be OK to rename it back. I dunno. The point is: users shouldn't be editing it anyway. What do you think? @dscho, can you foresee any problems if we do that?

**Comment by dscho** [comment]
The idea was to let users who want to edit their StartupMacros.txt do so, copying the contents from StartupMacros.fiji.ijm when they do. If there is a .txt, it would be used instead of the fiji.ijm. That way, the Fiji installation can be up-to-date even if the user has a "locally modified" StartupMacros.

Now, if you rename it back, every power user who modified StartupMacros.txt will have a problem because Fiji will say that there are locally modified files. And that's not a lie. @ctrueden clear?

**Comment by hinerm** [comment]
I have mixed feelings here. I appreciate the intent to encapsulate user/distributed macros but in my tests a local `StartupMacros.ijm` (or `.txt`) is not loaded on startup if there is a `StartupMacros.fiji.ijm` present. And putting stuff in `macros/AutoRun` adds it to the menus but also attempts to run the macro on startup, so it's not a perfect solution.

**Comment by ctrueden** [comment]
@dscho Thanks for the reminder. I agree that we should not rename it back.

@hinerm The "Startup Macros" command could be updated (either by us using imagej-legacy, or by Wayne I suppose) to also support `StartupMacros.fiji.ijm`. But I'd say this is a very low-priority task.

**Comment by hinerm** [comment]
>But I'd say this is a very low-priority task.

Agreed

**Comment by dscho** [comment]
> The "Startup Macros" command could be updated (either by us using imagej-legacy, or by Wayne I suppose) to also support StartupMacros.fiji.ijm.

Maybe like this?

https://github.com/imagej/ImageJA/blob/45050aacc6766ad09edc58481370be8d9a6f675c/src/main/java/ij/gui/Toolbar.java#L1368-L1378

**Comment by hinerm** [comment]
>Maybe like this?

Yeah, would need that logic [here](https://github.com/imagej/ImageJA/blob/v1.49v/src/main/java/ij/plugin/Commands.java#L152-L162)

**Comment by aschain** [comment]
I made these changes in my forked imagej, I don't know if they would be of interest:
https://github.com/aschain/imagej1/blob/master/ij/gui/Toolbar.java#L1368-L1384
and
https://github.com/aschain/imagej1/blob/master/ij/Menus.java#L1526-1535
and
https://github.com/aschain/imagej1/blob/master/ij/plugin/Commands.java#L158-161

I find this is best for editing Startupmacros in the fiji script editor by going to Plugins..Macros..Startupmacros.  (I also added back the ability for the script editor to install imagej 1 macros).

**Comment by ctrueden** [comment]
@aschain Thanks. Note that @rasband is the one who makes the call w.r.t. code in the ImageJ1 codebase. You could file your changes as a PR and see what he says.

**Comment by rasband** [comment]
The Plugins>Macros>Startup Macros command in the latest ImageJ daily build (1.51c1) opens StartupMacros.fiji.ijm if StartupMacros.txt and StartupMacros.ijm are not found. Changes can be viewed at https://github.com/imagej/imagej1/commit/74341c45c23d528c3f783928eb47b9790dd02cbf
