### ISSUE TITLE
Feature request: update the weaver

### ISSUE THREAD

**Issue by JonMarsh** [fiji/fiji#161]
For those of us who prefer to program in python, access to performant, pixel-wise algorithms is lacking with respect to ImageJ plugins written in pure Java, or compiled JavaScript or Groovy.  The weaver would conveniently fill this gap for the most part, especially for scripts that need to access pixel data arrays.  Given that jython scripting is widely used in the ImageJ community (and in many of the online tutorials, I think this would be a great feature to revive and would enhance scripting utility in general.

Thanks,

Jon Marsh

**Comment by ctrueden** [comment]
Fixing the [Jython weaver](https://github.com/fiji/weave_jy2java) probably entails solving imagej/imagej-ui-swing#48, as well as imagej/imagej#105. In other words: we need a robust way of compiling and running Java code dynamically. The current [scijava/scripting-java](https://github.com/scijava/scripting-java) unfortunately has several problems.

**Comment by acardona** [comment]
I've just pushed to master an update to the Weaver that drops dependencies altogether, not depending on ImageJ, the now obsolete Refresh_Javas compilation framework, or Fiji's Script Editor. See commit #933e7fa5eb0b.

Note the still implicit dependency on com.sun.tools.javac.Main from the tools.jar, which has to be included in the java classpath if not there. For example, when using openjdk-8 (java 8), launch Fiji like this to add the tools.jar to the classpath:

    ./ImageJ-linux64 --class-path /usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar --

While I am exploring other compilation options (e.g. javassist), the current one works well.

Note that I've added a new feature: an additional argument to pass a list of classes to import, so that scripts don't need to fully qualify class names. For example, instead of:

    net.imglib2.type.numeric.real.FloatType f = new net.imglib2.type.numeric.real.FloatType();

... now one can pass the FloatType class directly into the Weaver.inline invocation, and write code like:

    FloatType f = new FloatType();

... which is a lot more readable.

Future additions to the Weaver include defining methods, so that instead of a Callable, one would have a regular java object with specific methods to call. This can be useful to overcome some limitations in the way bindings are handled currently. Working on it.

**Comment by ctrueden** [comment]
> I am exploring other compilation options

Going forward, I would strongly suggest to use [scripting-java](https://github.com/scijava/scripting-java), which uses `javax.tools.JavaCompiler`, which is the officially supported way of compiling Java code via Java's public API. If that approach is insufficient for any reason, we can look at improving things at the `scripting-java` level so that everyone who needs to compile Java code benefits.

> I've added a new feature: an additional argument to pass a list of classes to import, so that inlined code doesn't need to fully qualify class names.

:+1:

**Comment by acardona** [comment]
The new feature Weaver.method is implemented: https://github.com/fiji/weave_jy2java/blob/master/src/main/java/fiji/scripting/Weaver.java#L248

**Comment by ctrueden** [comment]
I cut [a new release](http://maven.imagej.net/#nexus-search;gav~sc.fiji~weave_jy2java~2.1.0~~) and also [added it to the SciJava component collection](https://github.com/scijava/pom-scijava/commit/11f82f8fd367d1fd8f96b3d96cd90118d6ee6a34). I will upload it to the Java-8 update site later tonight, barring any objections. So I think this issue can be closed as resolved! Thanks @acardona for your efforts.

**Comment by JonMarsh** [comment]
Thank you @acardona and @ctrueden for so rapidly reviving this awesome feature!  It is much appreciated.

Jon
