### ISSUE TITLE
Fiji cannot import Ilastik hdf5

### ISSUE THREAD

**Issue by rejsmont** [fiji/fiji#163]
Hi again,

I have been trying to import some Ilastik probability maps in hdf5 format. Unfortunately, it seems that Fiji hdf5 importer cannot handle multichannel float32 images :( Any workarounds other than exporting tiffs from Ilastik?

![screen shot 2017-04-11 at 17 26 38](https://cloud.githubusercontent.com/assets/1191962/24917094/5dbc91d4-1edc-11e7-9c81-581730e2f65a.png)

**Comment by ctrueden** [comment]
Which HDF importer do you mean? Fiji does not ship with one.

Do you mean the HDF5 update site? The author stopped maintaining it, but gave permission for the Fiji community to continue doing so. So we forked it, and you can find the repository at [fiji/HDF5_Vibez](https://github.com/fiji/HDF5_Vibez). The current maintainer is @kmdouglass. 

In general, I suggest you post questions on the [ImageJ Forum](http://forum.imagej.net/), and use GitHub Issues specifically for bug reports and feature requests.

I'll close this issue, since it's not really about Fiji. You can either follow up on the forum, or else open a new issue in `fiji/HDF5_Vibez` if you like.
