### ISSUE TITLE
Problem with http://maven.imagej.net

### ISSUE THREAD

**Issue by kozusznik** [fiji/fiji#173]
Downloading stops for http://maven.imagej.net/content/groups/public/io/scif/scifio-jai-imageio/1.1.1/scifio-jai-imageio-1.1.1.jar at 654 KB. It also timeouts after few minutes.

**Comment by ctrueden** [comment]
@kozusznik Sounds like a network quality issue. I was able to download it successfully here. Are you still having problems?

**Comment by kozusznik** [comment]
Yes, It was probably network issue. I have switched to different provider and it goes correctly. Only one confusing thing is that other jars were downloaded without problem.

**Comment by ctrueden** [comment]
@kozusznik Glad you got it sorted. If it happens again in the future on any particular network, you can try using `https:` instead of `http:`; it might help, since some networks muck around with intermediate layers which can disrupt or modify plain `http:` traffic. But they can't do that with `https:` since it is encrypted. 😄
