### ISSUE TITLE
NIFTI image spacing information is ignored

### ISSUE THREAD

**Issue by nocnokneo** [fiji/fiji#191]
When opening a NIFTI image with pixel spacing, the information is ignored as can be seen from the `Analyze > Set Scale ...` dialog.

Using an up-to-date installation with ImageJ version 1.52b

**Comment by imagejan** [comment]
That's a `bio-formats` issue, since that is where `NiftiReader` is located:

https://github.com/openmicroscopy/bioformats/blob/develop/components/formats-gpl/src/loci/formats/in/NiftiReader.java

Please consider [reporting the bug to the bio-formats team](https://docs.openmicroscopy.org/bio-formats/5.8.2/about/bug-reporting.html).

**Comment by nocnokneo** [comment]
Thanks, I'll report the issue with them.

**Comment by ctrueden** [comment]
Thanks @nocnokneo. Please ping back here with a link to the reported issue, so that we can close this out while leaving a trail for anyone interested to follow.

**Comment by ctrueden** [comment]
@nocnokneo I saw your [message to ome-users](http://lists.openmicroscopy.org.uk/pipermail/ome-users/2018-May/007055.html). Thanks for following up, and for your patience.
