### ISSUE TITLE
Alt key changes focus on Windows10?

### ISSUE THREAD

**Issue by hyungsongnam** [fiji/fiji#206]
Hello,

So I found a strange behavior of Fiji in Windows 10, and am wondering if anybody knows how to fix it. I couldn't find anything through google searches on this one.

I open an image, and I use the hand tool with scroll, Shift - scroll, and Alt - scroll to look through different channels of the image at different zoom, and so on. This is excellent.

On Linux, I can do this smoothly without clicking on the image window.
On Windows 10, it seems that pressing the Alt key changes the window focus a second after the Alt key is released, i.e., the hand tool that is selected when I start this procedure changes to the arrow cursor. Then, the scroll doesn't work anymore. To make it work again, I need to click on the window once to bring it back, and then I can use the scroll.

I tried disabling the Alt key in windows registry, but this knocks out the Alt -scroll function altogether.

Any thoughts on fixing this? It would be much appreciated.

Thank you.

**Comment by imagejan** [comment]
The <kbd>Alt</kbd> in Windows generally activates the menu (try it in your browser, for example). Image windows in ImageJ don't have their own menu, but <kbd>Alt</kbd><kbd>Space</kbd> shows that the key acts the same as on other windows.

To work around this, you can simply press <kbd>Alt</kbd> once again, and you should get back the mouse cursor corresponding to your selected tool.

I don't know if this behavior is easy to change, but would suggest this issue belongs in [`imagej1`](https://github.com/imagej/imagej1) rather than `fiji`.

**Comment by hyungsongnam** [comment]
Thank you.

**Comment by hyungsongnam** [comment]
Found a solution
For Windows 10
Autohotkey script

LAlt up::
If (A_PriorKey = "LAlt") ;  If LAlt was pressed alone
    return ; do nothing
return

; In this case its necessary to define a custom combination by using "LAlt &" or "<!" 
; to avoid that LAlt loses its original function as a modifier key:

<!F4:: Send {Alt Down}{F4}{Alt Up} ; <! means LAlt

**Comment by hyungsongnam** [comment]
Found a solution for Windows 10
Autohotkey script

LAlt up::
If (A_PriorKey = "LAlt") ;  If LAlt was pressed alone
    return ; do nothing
return

; In this case its necessary to define a custom combination by using "LAlt &" or "<!" 
; to avoid that LAlt loses its original function as a modifier key:

<!F4:: Send {Alt Down}{F4}{Alt Up} ; <! means LAlt

Thanks.
HN
