### ISSUE TITLE
Linux Problem Maximizing Image Window

### ISSUE THREAD

**Issue by TomkoLA** [fiji/fiji#220]
System info:
Kernel: 4.19.0-1-amd64 x86_64 bits: 64 compiler: gcc v: 6.3.0 
           Desktop: Xfce 4.12.3 Distro: MX-18.1_x64 Continuum Feb 9  2019 
           base: Debian GNU/Linux 9 (stretch) 
FIJI: 1.52i and ImageJ: 1.52a with a Java8 runtime

Regardless of what file type I open (I have tried .avi and .tif recently), the image window will open at 50% size. However, when I want to increase the image size to as large as the screen will handle for analysis, the maximize button does not seem to work at all. I tried capturing any errors from FIJI with the Edit>Options>Misc>Debug Mode, but there didn't appear to be any. This problem is present in both the FIJI and ImageJ versions I have tried. I'm probably missing some system information here and would be happy to provide any additional missing clues that might help resolve this issue.

**Comment by imagejan** [comment]
What you describe has always been the behavior of ImageJ (and Fiji Is Just ImageJ). You can use <kbd>+</kbd> to change the size of the image.

I'm closing this since it's not a `fiji/fiji` issue. Feel free to suggest changes on `imagej/imagej1` to @rasband directly, or open a discussion [on the forum](https://forum.image.sc/tags/imagej).
