### ISSUE TITLE
Howto readout imagestitching variables

### ISSUE THREAD

**Issue by pettaa123** [fiji/fiji#228]
Hi, I would like to debug the image Grid Image stitching that is coming with fiji. Iam not a Java developer. I have installed Eclipse and managed to load fiji source code via maven into elipse. How do I add now the imagestitching correctly and start it then?

thanks :)

**Comment by pettaa123** [comment]
Hey, I start imagej out of the stitiching source from src/test/java/Main.java -> Debug As ->Java Application.
The "Grid/Collection stitching" menu appears. But the set breakpoints dont work. No matter where I set them in the sourcecode.

**Comment by ctrueden** [comment]
@pettaa123 There is more than one way to do it, but here is what I typically do:

1. Import fiji/fiji into Eclipse.
2. Import fiji/Stitching into Eclipse.
3. Edit the `pom.xml` of fiji/fiji, adding the line `<Stitching.version>3.1.7-SNAPSHOT</Stitching.version>` beneath the `<properties>` section (around line 177 as of this writing). This version should match the version in the fiji/Stitching project's `pom.xml`!
4. In that same `pom.xml` of fiji, click over to the Dependencies tab, scroll down, verifying that Stitching successfully transformed from a JAR icon to a folder icon—this means that your two projects are linked with a project coupling rather than a binary library coupling.
5. Launch Fiji in debug mode using the `Main` in the fiji/fiji project.
6. Set breakpoints anywhere you want in the Stitching project.
7. Run the Stitching plugin from the Fiji interface, and (hopefully!) enjoy Eclipse breaking at the proper spots.

**Comment by ctrueden** [comment]
@pettaa123 Also, just to clarify: launching the Stitching project's `Main` in debug mode should also work. I am not sure why that isn't working, but you can try the process I outlined above and see whether that makes any difference. Running the Stitching plugin's `Main` will launch an ImageJ with Stitching available, but not all the Fiji plugins, whereas the process I outlined is closer to running in "actual Fiji" because all the plugins should be there. But for debugging it may not make much difference. Either way, breakpoints should be working.

**Comment by pettaa123** [comment]
Thank you. It turned out that I my java jdk didnt contained the java source .zip

**Comment by StephanPreibisch** [comment]
Great, thanks a lot @ctrueden !
