### ISSUE TITLE
JFreeSVG jar file missing from the jars folder

### ISSUE THREAD

**Issue by acardona** [fiji/fiji#231]
It's available here, as source jar and compiled jar: https://repo1.maven.org/maven2/org/jfree/jfreesvg/3.3/

This jar is necessary for ```org.jfree.chart.util.ExportUtils.writeAsSVG``` to work.

Having this jar completes the JFreeChart library in a way that enables creating analytical charts from within Fiji trivially, storing them as SVG for both compactability and also editability.

**Comment by ctrueden** [comment]
I added JFreeSVG to the SciJava bill of materials: scijava/pom-scijava/commit/b9aebc24bc977f2fd20253ed5ffa8cfdaab07642

Certainly we can include the JFreeSVG library as part of Fiji. For other supporting libraries, though ,the approach has been that they become dependencies of Fiji transitively because some plugin depends on them. Do you have a particular plugin or script that will depend on JFreeSVG? Or you just want it available for one-off scripting?

**Comment by acardona** [comment]
Thanks @ctrueden. Even for just one-off scripting would be great. The ability to save ```JFreeChart``` as an SVG is wonderful.

**Comment by ctrueden** [comment]
Ahh, I addressed this with fiji/fiji@edd4e1cb5a013413d2b8106f73479409e21d22cf long ago, but I forgot to link it to this issue to close it out.
