### ISSUE TITLE
Frozen Fiji in Ubuntu 20.04 java 8u252

### ISSUE THREAD

**Issue by acardona** [fiji/fiji#250]
As explained here https://forum.image.sc/t/broken-fiji-in-ubuntu-20-04-with-openjdk-8u252/38099

Fiji launches but its UI is unresponsive: the event dispatch thread is blocked, as shown in the jconsole.

To blame, perhaps the ```org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:705)``` line of the event dispatch thread stack trace.

Haven't tried yet with a different desktop environment.

**Comment by axtimwalde** [comment]
Working with Fiji on Ubuntu 20.04 without problems, may be a local issue?

**Comment by axtimwalde** [comment]
@acardona That was premature, I did not read the full discussion and tested with 172.  For me the issue is only present if I try to click a UI element before the splash-logo disappears.  If I wait for it do go away, the UI keeps working.  This is not the case with 172 where the splash logo also goes away quicker.  Can you confirm?

**Comment by acardona** [comment]
I can confirm: if I launch ```Image-linux64 --system``` (runs java 8u252) and don't click anywhere until the Fiji window is open and ready, then the UI is responsive as expected. But if I click away to another application, then the UI, when ready, is frozen.

**Comment by ctrueden** [comment]
Fiji on Linux has shipped with Zulu JDK+FX 1.8.0.322 for quite some time now, so I think this issue can be safely closed.
