### ISSUE TITLE
Open samples does not work

### ISSUE THREAD

**Issue by tischi** [fiji/fiji#255]
`[File > Open Samples]` does not work for me: no image is shown.
OS: Mac

**Comment by ctrueden** [comment]
I noticed this as well. I'm clueless as to why, but will investigate soon.

**Comment by imagejan** [comment]
I also noticed that the menu entries are different now, e.g. instead of "Blobs (25K)" it now just says "Blobs".

Also, running this script works as expected:

```
import ij.plugin.URLOpener

new URLOpener().run("blobs.gif")
```

.. so it must be some issue with the *File > Open Samples* menu itself not calling the commands it is supposed to call (and reported to do so by the built-in search).

**Comment by imagejan** [comment]
I don't know what's going wrong here. My investigation so far only showed that getting the `ModuleInfo` from the `MenuService` and running it via the `ModuleService` works as expected:

```
#@ ModuleService modS
#@ MenuService menuS

import org.scijava.module.ModuleInfo

mainMenu = menuS.getMenu()
blobsMenu = mainMenu.getMenu("File>Open Samples>Blobs")
println blobsMenu
modS.run(blobsMenu.getModuleInfo(), true)
```

**Comment by ctrueden** [comment]
It might be related to the ij1-patcher / imagej-legacy bytecode manipulation logic. There is a hook for Open Samples commands, so that the "Cache Samples Images" command can work. I will dig tomorrow.

**Comment by imagejan** [comment]
> I also noticed that the menu entries are different now, e.g. instead of "Blobs (25K)" it now just says "Blobs".

For the record: that was a change in `1.53a` and is likely not related to this issue:

From https://imagej.net/notes.html:
> Removed file sizes from entries in the File>Open Samples> submenu. Macros that use the old entries (e.g. "Blobs (25K)") continue to work. 

---

Also: running e.g. *Blobs* from the search bar result (by clicking <kbd>Run</kbd>) works fine.

Running `run("Blobs");` (or `run("Blobs (25K)");`) in a macro doesn't load any image, same as the menu.

**Comment by ctrueden** [comment]
It was [a bug in Fiji itself](https://github.com/fiji/fiji/blob/fiji-2.1.0/src/main/java/sc/fiji/compat/SampleImageLoader.java#L45). The `SampleImageLoader` plugin injects itself over top of ImageJ1's "Open Samples" commands. The Blobs command becomes `fiji.SampleImageLoader("http://imagej.nih.gov/ij/images/blobs.gif")`. The `fiji.SampleImageLoader` class no longer exists; it is `sc.fiji.compat.SampleImageLoader` now. (`http://imagej.nih.gov/ij/images/blobs.gif` also does not work, but ImageJ takes care to rewrite it to a working URL later; see `ij.io.Opener#updateUrl(String)`.)

Fixed with 535f17e9a2598dded49efc19acd626b924734d32. Will release shortly.

**Comment by imagejan** [comment]
Thanks, @ctrueden!

As `imagej1` has [its own "Cache Sample Images" command](https://github.com/imagej/imagej1/blame/c875290ab562ea46803ab22a16fe82920d93f649/ij/Menus.java#L115) since a while now, is `sc.fiji.compat.SampleImageLoader` needed at all anymore?

**Comment by ctrueden** [comment]
> is sc.fiji.compat.SampleImageLoader needed at all anymore?

I don't know. I filed #260.
