### ISSUE TITLE
Could not write initial ImageJ.cfg

### ISSUE THREAD

**Issue by a571795529** [fiji/fiji#286]
can someone assist me?

**Comment by mkitti** [comment]
```
# ImageJ startup properties
maxheap = 700m
jvmargs =
```

**Comment by ctrueden** [comment]
@a571795529 I don't understand exactly what the problem was. If you can provide instructions to reproduce, please feel free to reopen the issue. It would helpful to know for example which operating system you are using, along with other details. See https://imagej.net/discuss/bugs#bug-reporting-best-practices
