### ISSUE TITLE
Beanshell 2.1.1 fixes CVE-2016-2510

### ISSUE THREAD

**Issue by mihelm** [fiji/fiji#353]
Hi

Beanshell has been updated to version 2.1.1, which fixes a remote execution issue present in version 2.1.0. That version is still used by Fiji.

https://github.com/beanshell/beanshell/releases

https://github.com/advisories/GHSA-gxg6-rc6c-v673

Beanshell 2.1.0 also causes Fiji to be flagged by VirusTotal.

**Comment by ctrueden** [comment]
@mihelm I'm confused. [CVE-2016-2510](https://www.cve.org/CVERecord?id=CVE-2016-2510) is 8.5 years old, and is fixed by bsh 2.0b6, which is older than 2.1.0, isn't it? Nonetheless, I updated `org.scijava:scripting-beanshell` to depend on `org.apache-extras.beanshell:bsh` version 2.1.1, released a new version, and uploaded to the core update site.
