### ISSUE TITLE
Links in the Dev Menu lead to outdated URLs

### ISSUE THREAD

**Issue by amletierce** [fiji/fiji#359]
Currently the resources in the developer options menu link to https://imagej.nih.gov/ or other outdated sources. 
Please update these links to direct to the most current imagej website.

![image](https://github.com/user-attachments/assets/33e2c353-455f-4b38-9f02-4d038f6a6e1d)

**Comment by ctrueden** [comment]
@amletierce Thank you for the report. What version of Fiji are you using? Please run Help &rarr; Update... to bring your Fiji fully up to date, then (after restarting the program) click the status bar. It should say "(Fiji Is Just) ImageJ 2.14.0/1.54f, and the Help menu should read like this: 
![image](https://github.com/user-attachments/assets/2ad9db9e-4b7e-468a-9378-e79875520cdd)
On my system, these links go to imagej.net, not imagej.nih.gov. Do you still observe otherwise after updating?

**Comment by amletierce** [comment]
@ctrueden The issue persists after updating. My 'Help' menu looks like yours, but I meant to highlight the 'Dev' menu on the main toolbar (indicated by the red arrow).

<img width="568" alt="image" src="https://github.com/user-attachments/assets/fb8f1395-e236-4e9d-bfe5-b015a3f2f6ec">

**Comment by imagejan** [comment]
The URLs are hardcoded here:

https://github.com/fiji/fiji/blob/40d284a1039f66ef1ba53201a7192f024e42b485/macros/StartupMacros.fiji.ijm#L89-L117

**Comment by ctrueden** [comment]
@amletierce Ahh, sorry for misunderstanding the issue! And thank you @imagejan for pointing out the source of that toolbar button. Fixed now with d3ced5c0fe466279021004488aa0639be59909db; will be part of the upcoming Fiji-with-Java-21 ("Fiji Future") release.
